---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024

provisioner:
  name: chef_zero
  environments_path: test/environments
  roles_path: test/roles
  client_rb:
    solo: false

driver_config:
  require_chef_omnibus: 12.17.44

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    driver:
      vm_hostname: origin-centos-72

suites:
  - name: standalone
    run_list:
      - role[openshift3-base]
    verifier:
      inspec_tests:
        - test/inspec/standalone
        - test/inspec/shared
    attributes:
      openshift3-shared: &SHARED
        # use experimental repository while https://github.com/openshift/origin/issues/12567 is open
        yum_repositories:
          - name: "centos-openshift-origin"
            baseurl: "http://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin/"
            gpgcheck: false
        # we override these because 10.0.2.15 is whitelisted in $no_proxy
        openshift_common_public_hostname: 10.0.2.15
        openshift_master_router_subdomain: cloudapps.10.0.2.15.nip.io
        ose_major_version: 1.4
        docker_log_driver: journald
        persistent_storage:
        - name: testpv
          capacity: 100Mi
          access_modes: ReadOnlyMany
          path: /srv/testpv
          server: 10.0.2.15
          claim:
            namespace: default
        - name: registry-storage
          capacity: 100Mi
          access_modes: ReadWriteMany
          path: /srv/registry-storage
          server: 10.0.2.15
          claim:
            namespace: default
        registry_persistent_volume: registry-storage
        master_servers: &SERVERS
         - ipaddress: 10.0.2.15
           fqdn: origin-centos-72
           labels: region=infra custom=label
           schedulable: false
        node_servers: *SERVERS
      cookbook-openshift3:
        << : *SHARED
        openshift_HA: false

  - name: cluster-native
    run_list:
      - role[openshift3-base]
    verifier:
      inspec_tests:
        - test/inspec/cluster-native
        - test/inspec/shared
    attributes:
      cookbook-openshift3:
        << : *SHARED
        openshift_HA: true
        openshift_cluster_name: test-cluster.domain.local
        etcd_servers: *SERVERS
